"""create core tables

Revision ID: f4a42d6d7297
Revises: d3437ae947fe
Create Date: 2026-06-02 14:46:08.059559

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "f4a42d6d7297"
down_revision: Union[str, Sequence[str], None] = "d3437ae947fe"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "etl_runs",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("job_name", sa.Text(), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("status", sa.Text(), nullable=False),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("meta", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "players",
        sa.Column("id", sa.BigInteger(), autoincrement=False, nullable=False),
        sa.Column("full_name_en", sa.Text(), nullable=False),
        sa.Column("full_name_ko", sa.Text(), nullable=False),
        sa.Column("position", sa.Text(), nullable=False),
        sa.Column("player_type", sa.Text(), nullable=False),
        sa.Column("current_team_id", sa.BigInteger(), nullable=True),
        sa.Column("current_level", sa.Text(), nullable=True),
        sa.Column("is_active", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column("birth_date", sa.Date(), nullable=True),
        sa.Column("bats", sa.CHAR(length=1), nullable=True),
        sa.Column("throws", sa.CHAR(length=1), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "teams",
        sa.Column("id", sa.BigInteger(), autoincrement=False, nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("abbrev", sa.Text(), nullable=False),
        sa.Column("league", sa.Text(), nullable=True),
        sa.Column("level", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "game_logs",
        sa.Column("player_id", sa.BigInteger(), nullable=False),
        sa.Column("game_id", sa.BigInteger(), nullable=False),
        sa.Column("game_date", sa.Date(), nullable=False),
        sa.Column("opponent_id", sa.BigInteger(), nullable=True),
        sa.Column("is_home", sa.Boolean(), nullable=True),
        sa.Column("group_name", sa.Text(), nullable=False),
        sa.Column("stats", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "fetched_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["player_id"],
            ["players.id"],
        ),
        sa.PrimaryKeyConstraint("player_id", "game_id", "group_name"),
    )
    op.create_index(
        "idx_game_logs_date", "game_logs", [sa.literal_column("game_date DESC")], unique=False
    )
    op.create_index(
        "idx_game_logs_player_date",
        "game_logs",
        ["player_id", sa.literal_column("game_date DESC")],
        unique=False,
    )
    op.create_table(
        "season_stats",
        sa.Column("player_id", sa.BigInteger(), nullable=False),
        sa.Column("season", sa.Integer(), nullable=False),
        sa.Column("group_name", sa.Text(), nullable=False),
        sa.Column("stats", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "fetched_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["player_id"],
            ["players.id"],
        ),
        sa.PrimaryKeyConstraint("player_id", "season", "group_name"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("season_stats")
    op.drop_index("idx_game_logs_player_date", table_name="game_logs")
    op.drop_index("idx_game_logs_date", table_name="game_logs")
    op.drop_table("game_logs")
    op.drop_table("teams")
    op.drop_table("players")
    op.drop_table("etl_runs")
    # ### end Alembic commands ###
