/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/players": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Players */
        get: operations["list_players_api_v1_players_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/players/{player_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Player */
        get: operations["get_player_api_v1_players__player_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/players/{player_id}/games": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Player Games */
        get: operations["list_player_games_api_v1_players__player_id__games_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** GameLogOut */
        GameLogOut: {
            /** Game Id */
            game_id: number;
            /**
             * Game Date
             * Format: date
             */
            game_date: string;
            /** Opponent Id */
            opponent_id: number | null;
            /** Is Home */
            is_home: boolean | null;
            /** Group Name */
            group_name: string;
            /** Stats */
            stats: {
                [key: string]: unknown;
            };
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * PlayerDetailOut
         * @description Player detail: summary plus bio and season totals.
         */
        PlayerDetailOut: {
            /** Id */
            id: number;
            /** Full Name En */
            full_name_en: string;
            /** Full Name Ko */
            full_name_ko: string;
            /** Position */
            position: string;
            /** Player Type */
            player_type: string;
            /** Current Team Id */
            current_team_id: number | null;
            /** Current Level */
            current_level: string | null;
            /** Is Active */
            is_active: boolean;
            /** Bats */
            bats: string | null;
            /** Throws */
            throws: string | null;
            /** Birth Date */
            birth_date: string | null;
            /** Season Stats */
            season_stats: components["schemas"]["SeasonStatsOut"][];
        };
        /**
         * PlayerOut
         * @description Player summary for the list endpoint / cards.
         */
        PlayerOut: {
            /** Id */
            id: number;
            /** Full Name En */
            full_name_en: string;
            /** Full Name Ko */
            full_name_ko: string;
            /** Position */
            position: string;
            /** Player Type */
            player_type: string;
            /** Current Team Id */
            current_team_id: number | null;
            /** Current Level */
            current_level: string | null;
            /** Is Active */
            is_active: boolean;
        };
        /** SeasonStatsOut */
        SeasonStatsOut: {
            /** Season */
            season: number;
            /** Group Name */
            group_name: string;
            /** Stats */
            stats: {
                [key: string]: unknown;
            };
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    list_players_api_v1_players_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlayerOut"][];
                };
            };
        };
    };
    get_player_api_v1_players__player_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                player_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlayerDetailOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_player_games_api_v1_players__player_id__games_get: {
        parameters: {
            query?: {
                since?: string | null;
            };
            header?: never;
            path: {
                player_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GameLogOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
}
